--- # Testing the J2 Template Module

- hosts: all
  connection: ssh
  user: ansible
  sudo: yes
  gather_facts: yes
  vars:
    userName: ansile
    userPassword: password123
    connectionType: ssh
  tasks:
    - name: Install the configuration file customized for the system
      template: src=file.conf.j2 dest=/home/ansible/file.conf owner=ansible group=ansible mode=750
