---
- hosts: local
  tasks:
   - name: install apache
     yum: pkg=httpd state=latest
   - name: verify services
     shell: systemctl status httpd
     register: result
     until: result.stdout.find("active (running)") != -1
     retries: 5
     delay: 5
   - debug: var=result
