---
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars_files:
    - files.yml
  tasks:
    - name: install httpd with using variable file
      yum: name={{ pkg }} state=installed

